import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Dz Event - Découvrz les meilleurs événements en Algérie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header style={{ padding: '16px', background: '#1f1813', color: '#f4e8d8' }}>
          <h1>DZ Events</h1>
          <nav>
            <a href="/">Accueil</a> | <a href="/events">Événements</a>
          </nav>
        </header>

        <main style={{ minHeight: 'calc(100vh - 120px)' }}>
          {children}
        </main>

        <footer style={{ padding: '16px', textAlign: 'center', background: '#1f1813', color: '#c7b59f' }}>
          © 2026 DZ Events by Amine ZIDELMAL
        </footer>
      </body>
    </html>
  );
}
